# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created: Mon Oct  5 16:51:51 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 580)
        Dialog.setMaximumSize(QtCore.QSize(800, 580))
        Dialog.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.xval = QtGui.QLabel(Dialog)
        self.xval.setFrameShape(QtGui.QFrame.StyledPanel)
        self.xval.setFrameShadow(QtGui.QFrame.Sunken)
        self.xval.setObjectName("xval")
        self.gridLayout.addWidget(self.xval, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.counts = QtGui.QLabel(Dialog)
        self.counts.setFrameShape(QtGui.QFrame.StyledPanel)
        self.counts.setFrameShadow(QtGui.QFrame.Sunken)
        self.counts.setObjectName("counts")
        self.gridLayout.addWidget(self.counts, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.background = QtGui.QLabel(Dialog)
        self.background.setFrameShape(QtGui.QFrame.StyledPanel)
        self.background.setFrameShadow(QtGui.QFrame.Sunken)
        self.background.setObjectName("background")
        self.gridLayout.addWidget(self.background, 3, 1, 1, 1)
        self.yval = QtGui.QLabel(Dialog)
        self.yval.setFrameShape(QtGui.QFrame.StyledPanel)
        self.yval.setFrameShadow(QtGui.QFrame.Sunken)
        self.yval.setObjectName("yval")
        self.gridLayout.addWidget(self.yval, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.qtframe = QtGui.QFrame(Dialog)
        self.qtframe.setMinimumSize(QtCore.QSize(200, 200))
        self.qtframe.setMaximumSize(QtCore.QSize(200, 200))
        self.qtframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qtframe.setFrameShadow(QtGui.QFrame.Raised)
        self.qtframe.setObjectName("qtframe")
        self.vis = MPL_Widget1(self.qtframe)
        self.vis.setGeometry(QtCore.QRect(0, 0, 200, 200))
        self.vis.setMinimumSize(QtCore.QSize(200, 200))
        self.vis.setMaximumSize(QtCore.QSize(200, 200))
        self.vis.setObjectName("vis")
        self.horizontalLayout.addWidget(self.qtframe)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radprof = MPL_Widget(self.tab_3)
        self.radprof.setMinimumSize(QtCore.QSize(300, 0))
        self.radprof.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.radprof.setObjectName("radprof")
        self.verticalLayout_2.addWidget(self.radprof)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horcut = MPL_Widget(self.tab_4)
        self.horcut.setMinimumSize(QtCore.QSize(300, 0))
        self.horcut.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.horcut.setObjectName("horcut")
        self.verticalLayout_3.addWidget(self.horcut)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vertcut = MPL_Widget(self.tab_5)
        self.vertcut.setMinimumSize(QtCore.QSize(300, 0))
        self.vertcut.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.vertcut.setObjectName("vertcut")
        self.verticalLayout_4.addWidget(self.vertcut)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "X Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Y Center", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Counts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Radial Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "Vertical", None, QtGui.QApplication.UnicodeUTF8))

from mpl_pyqt4_widget import MPL_Widget
from mpl_pyqt4_widget_new import MPL_Widget1
