# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NTV.ui'
#
# Created: Mon Oct  5 15:28:50 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NTV(object):
    def setupUi(self, NTV):
        NTV.setObjectName("NTV")
        NTV.resize(1103, 609)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 221, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 221, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 221, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 221, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        NTV.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sole.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NTV.setWindowIcon(icon)
        NTV.setAnimated(True)
        NTV.setDocumentMode(False)
        self.centy = QtGui.QWidget(NTV)
        self.centy.setAcceptDrops(True)
        self.centy.setObjectName("centy")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centy)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 430, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filelab = QtGui.QLabel(self.centy)
        self.filelab.setMinimumSize(QtCore.QSize(400, 0))
        self.filelab.setMaximumSize(QtCore.QSize(400, 16777215))
        self.filelab.setObjectName("filelab")
        self.horizontalLayout.addWidget(self.filelab)
        self.pushButton = QtGui.QPushButton(self.centy)
        self.pushButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_3 = QtGui.QLabel(self.centy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.sizeofcut = QtGui.QLineEdit(self.centy)
        self.sizeofcut.setMinimumSize(QtCore.QSize(75, 0))
        self.sizeofcut.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sizeofcut.setObjectName("sizeofcut")
        self.horizontalLayout.addWidget(self.sizeofcut)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtGui.QFrame(self.centy)
        self.frame.setMaximumSize(QtCore.QSize(214, 524))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.minipix = QtGui.QLabel(self.frame)
        self.minipix.setMinimumSize(QtCore.QSize(200, 200))
        self.minipix.setMaximumSize(QtCore.QSize(200, 200))
        self.minipix.setFrameShape(QtGui.QFrame.StyledPanel)
        self.minipix.setFrameShadow(QtGui.QFrame.Raised)
        self.minipix.setObjectName("minipix")
        self.verticalLayout.addWidget(self.minipix)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.minlab = QtGui.QLabel(self.frame)
        self.minlab.setMaximumSize(QtCore.QSize(140, 40))
        self.minlab.setFrameShape(QtGui.QFrame.StyledPanel)
        self.minlab.setFrameShadow(QtGui.QFrame.Sunken)
        self.minlab.setObjectName("minlab")
        self.gridLayout.addWidget(self.minlab, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.maxlab = QtGui.QLabel(self.frame)
        self.maxlab.setMaximumSize(QtCore.QSize(140, 40))
        self.maxlab.setFrameShape(QtGui.QFrame.StyledPanel)
        self.maxlab.setFrameShadow(QtGui.QFrame.Sunken)
        self.maxlab.setObjectName("maxlab")
        self.gridLayout.addWidget(self.maxlab, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.xdim = QtGui.QLabel(self.frame)
        self.xdim.setMaximumSize(QtCore.QSize(140, 40))
        self.xdim.setFrameShape(QtGui.QFrame.StyledPanel)
        self.xdim.setFrameShadow(QtGui.QFrame.Sunken)
        self.xdim.setObjectName("xdim")
        self.gridLayout.addWidget(self.xdim, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.ydim = QtGui.QLabel(self.frame)
        self.ydim.setMaximumSize(QtCore.QSize(140, 40))
        self.ydim.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ydim.setFrameShadow(QtGui.QFrame.Sunken)
        self.ydim.setObjectName("ydim")
        self.gridLayout.addWidget(self.ydim, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.pixval = QtGui.QLabel(self.frame)
        self.pixval.setMaximumSize(QtCore.QSize(140, 40))
        self.pixval.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pixval.setFrameShadow(QtGui.QFrame.Sunken)
        self.pixval.setObjectName("pixval")
        self.gridLayout.addWidget(self.pixval, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lincheck = QtGui.QRadioButton(self.frame)
        self.lincheck.setObjectName("lincheck")
        self.horizontalLayout_3.addWidget(self.lincheck)
        self.logcheck = QtGui.QRadioButton(self.frame)
        self.logcheck.setObjectName("logcheck")
        self.horizontalLayout_3.addWidget(self.logcheck)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.cmapbox = QtGui.QComboBox(self.frame)
        self.cmapbox.setObjectName("cmapbox")
        self.verticalLayout.addWidget(self.cmapbox)
        self.horizontalLayout_2.addWidget(self.frame)
        self.imshow = MPL_Widget(self.centy)
        self.imshow.setMinimumSize(QtCore.QSize(650, 450))
        self.imshow.setObjectName("imshow")
        self.horizontalLayout_2.addWidget(self.imshow)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.centy)
        self.label.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.clipslide = QtGui.QSlider(self.centy)
        self.clipslide.setOrientation(QtCore.Qt.Vertical)
        self.clipslide.setObjectName("clipslide")
        self.verticalLayout_2.addWidget(self.clipslide)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        NTV.setCentralWidget(self.centy)
        self.menubar = QtGui.QMenuBar(NTV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuImage = QtGui.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        NTV.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(NTV)
        self.statusbar.setObjectName("statusbar")
        NTV.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(NTV)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtGui.QAction(NTV)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHeader = QtGui.QAction(NTV)
        self.actionHeader.setObjectName("actionHeader")
        self.actionAbout = QtGui.QAction(NTV)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHeader_2 = QtGui.QAction(NTV)
        self.actionHeader_2.setObjectName("actionHeader_2")
        self.actionPreferences = QtGui.QAction(NTV)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionBlink = QtGui.QAction(NTV)
        self.actionBlink.setObjectName("actionBlink")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuImage.addAction(self.actionHeader_2)
        self.menuImage.addAction(self.actionBlink)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(NTV)
        QtCore.QMetaObject.connectSlotsByName(NTV)

    def retranslateUi(self, NTV):
        NTV.setWindowTitle(QtGui.QApplication.translate("NTV", "NTV", None, QtGui.QApplication.UnicodeUTF8))
        self.filelab.setText(QtGui.QApplication.translate("NTV", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("NTV", "Pick Star", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NTV", "Aperture Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NTV", "Min Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NTV", "Max Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NTV", "X Dim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("NTV", "Y Dim", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NTV", "Pixel Value", None, QtGui.QApplication.UnicodeUTF8))
        self.lincheck.setText(QtGui.QApplication.translate("NTV", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.logcheck.setText(QtGui.QApplication.translate("NTV", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NTV", "Clip Point", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("NTV", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("NTV", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImage.setTitle(QtGui.QApplication.translate("NTV", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("NTV", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("NTV", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("NTV", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeader.setText(QtGui.QApplication.translate("NTV", "Header", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeader.setShortcut(QtGui.QApplication.translate("NTV", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("NTV", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeader_2.setText(QtGui.QApplication.translate("NTV", "Header", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHeader_2.setShortcut(QtGui.QApplication.translate("NTV", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("NTV", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlink.setText(QtGui.QApplication.translate("NTV", "Blink", None, QtGui.QApplication.UnicodeUTF8))

from mpl_pyqt4_widget import MPL_Widget
import icons_rc
